import turtle
import random
scn = turtle.Screen()
scn.bgcolor("black")
scn.screensize(500 , 500)
scn.title("Guess the Flag!!!")
t1 = turtle.Turtle()
lives = 3
points = 0

def Japan():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("white")
    t1.begin_fill()
    for i in range(2):
        t1.forward(200)
        t1.right(90)
        t1.forward(150)
        t1.right(90)
        t1.penup()
    t1.end_fill()
    t1.goto(100,-125)
    t1.fillcolor("red")
    t1.begin_fill()
    t1.pendown()
    t1.circle(50)
    t1.end_fill()


def Italy():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("green")
    t1.begin_fill()
    for i in range(2):
        t1.forward(75)
        t1.right(90)
        t1.forward(150)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(75, 0)
    t1.pendown()
    t1.fillcolor("white")
    t1.begin_fill()
    for i in range(2):
        t1.forward(75)
        t1.right(90)
        t1.forward(150)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(150, 0)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(75)
        t1.right(90)
        t1.forward(150)
        t1.right(90)
    t1.end_fill()


def France():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("blue")
    t1.begin_fill()
    for i in range(2):
        t1.forward(75)
        t1.right(90)
        t1.forward(150)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(75, 0)
    t1.pendown()
    t1.fillcolor("white")
    t1.begin_fill()
    for i in range(2):
        t1.forward(75)
        t1.right(90)
        t1.forward(150)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(150, 0)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(75)
        t1.right(90)
        t1.forward(150)
        t1.right(90)
    t1.end_fill()

def Germany():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("black")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(75, 0)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(75, -33.33)
    t1.pendown()
    t1.fillcolor("yellow")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()

def Austria():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -33.33)
    t1.pendown()
    t1.fillcolor("white")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -66.66)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()

def Spain():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -33.33)
    t1.pendown()
    t1.fillcolor("yellow")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -66.66)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()

def Russia():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("white")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -33.33)
    t1.pendown()
    t1.fillcolor("blue")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -66.66)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()

def Poland():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("white")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -33.33)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()

def Estonia():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("blue")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -33.33)
    t1.pendown()
    t1.fillcolor("black")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -66.66)
    t1.pendown()
    t1.fillcolor("white")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()

def Bulgaria():
    t1.penup()
    t1.goto(0, 0)
    t1.pendown()
    t1.fillcolor("white")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -33.33)
    t1.pendown()
    t1.fillcolor("green")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()
    t1.penup()
    t1.goto(0, -66.66)
    t1.pendown()
    t1.fillcolor("red")
    t1.begin_fill()
    for i in range(2):
        t1.forward(150)
        t1.right(90)
        t1.forward(33.33)
        t1.right(90)
    t1.end_fill()

countries = [Germany,Spain,Japan,Italy,France,Austria,Russia,Poland,Estonia,Bulgaria]

while lives > 0 and len(countries) > 0:
    t1.reset()
    flag = random.choice(countries)
    flag()
    answer = input("Guess the flag! ")
    if answer == flag.__name__:
        print("Correct!")
        points = points + 1
        countries.remove(flag)
    else:
        print("Wrong!")
        lives = lives - 1

    print("Points: ", points)
    print("Lives: ", lives)

print("Game over")


turtle.done()